### ISSUE TITLE
Requesting update on the state of this module

### ISSUE THREAD

**Issue by fritzfr** [react-native-kit/react-native-track-player#1074]
Hey everybody,

I'm wondering whether this module is still being developed.
There is **a lot** of open issues, some of which make the player close to unusable in production to be honest. Most issues don't have any comments from the maintainers. In general, it doesn't look like the module is getting much attention.
There is also the 2.x branch, which looked like it was supposed to succeed the 1.x branch, but nothing much is happening there either.

So to the maintainers of this module: Could you provide us with an update on the state of development/future plans? Otherwise there is no point anymore in opening tickets and trying to implement this in apps that would like to reach production.

Cheers

**Comment by fritzfr** [comment]
Well this says a lot.

**Comment by puckey** [comment]
> Well this says a lot.

Why so snarky?

**Comment by puckey** [comment]
I think it is pretty clear that this project is currently under-maintained. If you want to contribute, there are a bunch of open issues that you could take on. I would suggest focusing on the ‘dev’ branch, since it has seen the most work recently. We all look forward to your contributions! Probably the discord would be the best place for further broad discussions.
