### ISSUE TITLE
TrackPlayer.CAPABILITY_SEEK_TO doesn't do anything

### ISSUE THREAD

**Issue by Nivekiba** [react-native-kit/react-native-track-player#265]
When i set the seek_to capability nothing appears in my notification bar unless play and pause button...
So with this issue i can handle "remote-seek" event since it's not caught.

I'm testing my app on Android 7.0 Infinix

**Comment by djmMax** [comment]
Same for me. I've an Android 7.0 and 4.4

**Comment by Nivekiba** [comment]
@Guichaguri 😢 😭

**Comment by maendamedia** [comment]
I do not get the whole library to work in Android :(
Anyone ideas? I keep getting errors when starting the simulator about not finding things

**Comment by Guichaguri** [comment]
Does it still happens on 1.0.0?

**Comment by Guichaguri** [comment]
The notification is not the only remote media control available, because of that, I've been adding events to other media controls that can be used in Android. Android Wear, Android Auto and a few other devices may show a progress bar which can be used to seek to a specific position.

It seems to be working as expected, it's just not available as a feature for the notification.
