### ISSUE TITLE
Could Android both use `TrackPlayer.eventEmitter` and `HeadlessJsTaskService`?

### ISSUE THREAD

**Issue by anderslemke** [react-native-kit/react-native-track-player#33]
Or maybe some other way of making the event handling more homogeneous?

**Comment by Guichaguri** [comment]
We are working on that, figuring out a way to make both of them work together without weird setups or performance issues

**Comment by Guichaguri** [comment]
Here is the problem: The most friendly design would be having `on`, `off`, `once` functions, just like [nodejs events](https://nodejs.org/api/events.html), and that can easily work with the event emitter, but not with the headless task as it needs to be registered.

I *can* replace the headless task with an event emitter, but the point of being a headless task is to work in background, while the app is closed.

How can we make it easy, convenient and as fast as possible?

Here are a few ideas:
* Make iOS work exactly like the headless task (not convenient)
* Add `on`, `off`, `once` functions, but having to add a call in the index that registers the headless task (ugly solution, and can end up in memory leaks)
* Categorize events: Use the event emitter for "UI-based events" and the headless task for the rest of them (still not very convenient, also makes it confusing)

**Comment by Guichaguri** [comment]
I've been thinking about this. The best solution would be making iOS and Windows work like the headless task: one function that receives all the events.

Here is why: it wouldn't end up in memory leaks (developers forgetting to remove the event handlers from react components), would force them to add a call that can register the headless task, would work in background and after the app is closed, and encourage the use of a state container (redux, mobx, etc) to store/spread the event data throughout the app.

@dcvz What do you think?

**Comment by dcvz** [comment]
What we could do is keep things as they are now.. native layer emits different events (it keeps the main logic reasonable). At the JS level we could have listeners for these and emit everything to one place (maybe using [this](https://github.com/asyncly/EventEmitter2)) which would provide one centralised place for the user to listen to unified messages :)

**Comment by Guichaguri** [comment]
I thought about that, but it can cause many problems in Android:
* Registering: The Headless task should be registered at the same part that the main react component is registered. The app dev would have to add a function call there for the Android EventEmitter to register itself.
* Memory Leaks: It's pretty easy to add listeners inside react components and forget to remove them, in Android, those listeners would make the component object never be removed, even after the app is closed.
* Too many listeners: App devs would want to have one listener for each react component to update them accordingly instead of using a state container, which is a bad practice, as the memory usage would go higher, react would have to re-render for every single event listener, and it would probably end up in unmaintainable code.

I agree that an EventEmitter is way nicer to work with, but it won't work well with Headless JS.

**Comment by Guichaguri** [comment]
Android, iOS and Windows events are now unified. Learn how to use the new event system [here](https://github.com/react-native-kit/react-native-track-player/wiki/API#receiving-events)
