### ISSUE TITLE
Unable to run example Error 500

### ISSUE THREAD

**Issue by haithem-rihane** [react-native-kit/react-native-track-player#398]
Hello All,

I tried to run the example on my physical device i got this error:

`react-native start`

![image](https://user-images.githubusercontent.com/2827416/51428779-06264c00-1c08-11e9-9a0a-4a645c171b51.png)

`react-native run-android`

![screenshot_20190119-163039](https://user-images.githubusercontent.com/2827416/51428808-50a7c880-1c08-11e9-9e5b-18f62687c95c.jpg)

Thanks in Advance

**Comment by Guichaguri** [comment]
This issue usually happens when you install react-native both on the example app and inside `react-native-track-player`.
To fix it, you can delete the `node_modules` directory from `react-native-track-player` (in /example/node_modules/react-native-track-player/node_modules)

If that doesn't fix the issue, can you send the full logs from the metro bundler window?
