### ISSUE TITLE
Ignore Malformed Tracks in `add`

### ISSUE THREAD

**Issue by dcvz** [react-native-kit/react-native-track-player#457]
When queueing tracks and one track is malformed, the whole queue is rejected. Perhaps the player, should just skip over malformed tracks and add those it can.

**Comment by Guichaguri** [comment]
I don't see a reason for this. I think the error message is only ever seen in development, and it guides the app developer on how they should create track objects.

It's also a better practice to show an error whenever something is wrong, adding it partially might confuse the app developers instead of guiding them to the error.
