### ISSUE TITLE
[Notification feature request] Allow dismising notification if the player is paused

### ISSUE THREAD

**Issue by timmywil** [react-native-kit/react-native-track-player#459]
Currently, the notification player is always sticky, even if the music is paused and even when you force quit the app, probably because a track is still in the queue in the native player.

Spotify does this with their notification player. If the player is paused, the notification can be dismissed. When music is playing, the notification is sticky. I don't know that much about native Android, but I imagine this is some setting for the notification.

**Comment by Guichaguri** [comment]
The reason why Spotify does this is because the music service is not directly linked to the app, both of them can run independently.
This has been discussed before and it is possible to implement a workaround, but it's a big solution for a small problem. As we're focusing on stability first at the moment, we'll hold that to another time.

See https://github.com/react-native-kit/react-native-track-player/issues/307#issuecomment-452803916
