### ISSUE TITLE
ExoPlayer does not work well on many Amazon devices.

### ISSUE THREAD

**Issue by curiousdustin** [react-native-kit/react-native-track-player#545]
ExoPlayer seems to fail to various degrees on various Amazon devices I have tried. Some work decently, and others will simply refuse to play audio. I have only tried Kindle devices, but my research indicates that other devices would likely have issues as well.

When I started researching this, I found that this is due to the ExoPlayer team not providing support for Amazon's fork of Android.

In response, Amazon has created a port of ExoPlayer to be used on their devices.

https://developer.amazon.com/docs/fire-tv/media-players.html#exoplayer

https://github.com/amzn/exoplayer-amazon-port

**Comment by curiousdustin** [comment]
I have addressed this in my own fork of this repo. 

https://github.com/curiousdustin/react-native-track-player/tree/curious

I have created a PR for those that are interested. #546 

This PR is not necessarily meant to be merged. I would like others to give input. I am new to Android build variants and such, I am not sure that it is necessarily the best generic approach for this library, but it does seem to work for my specific project.

**Comment by Guichaguri** [comment]
I hate how we need two different versions of the same library just to make an app work with regular Android devices and Fire OS ones, but what else we can do 🤷‍♂️

Unfortunately, Google doesn't support those devices because Fire OS is a fork of Android that doesn't pass the [Android CTS](https://source.android.com/compatibility/cts). I've found [these](https://github.com/google/ExoPlayer/issues/972#issuecomment-160692560) [statements](https://github.com/google/ExoPlayer/issues/392#issuecomment-92494484) about it.

**Comment by curiousdustin** [comment]
@Guichaguri's [solution](https://github.com/react-native-kit/react-native-track-player/pull/547#issuecomment-485053091) worked well for me so far. I created a PR to add a docs page for this. #560
