### ISSUE TITLE
Error handling when network fails

### ISSUE THREAD

**Issue by sideokyou** [react-native-kit/react-native-track-player#570]
Hi,

Actually, this is not a bug or issue. 

I couldn't find the information regard to error handling when network fail. If I use streaming URL for playing radio, but for some reason, the network failed. Do RNTP callbacks or has a function to handle that? 

I am kind of thinking to use `NetInfo`, and monitoring network status. However, I am not sure this is the perfect solution for handling this.

Any idea?

**Comment by Guichaguri** [comment]
I think [`playback-error`](https://react-native-kit.github.io/react-native-track-player/documentation/#playback-error) is what you're looking for.

**Comment by mitchdowney** [comment]
@Guichaguri, I am running into an issue where the playback-error event is not being called, even when I use fake audio file URLs. For example in my registered events I have:

```
PVTrackPlayer.addEventListener('playback-error', (x) => console.log('playback error', x))
```

And elsewhere I load the TrackPlayer using:

```
await TrackPlayer.add({
  id,
  url: 'http://fakelink.not.real/example.mp1234',
  title,
  artist,
  artwork
})
```

But when I run that code, the playback-error event is never called.

Meanwhile I have another event listener registered for playback-state, and that is called on load and when I hit play/pause. On load, the playback-state says it is "ready", which seems incorrect to me, since it is trying to reach a non-existent file, I would think the state should be "error" or "none".

Is this a bug in the code? Or could I have something configured incorrectly?

Thanks for all your work on react-native-track-player :) it's great stuff
