### ISSUE TITLE
'remote-skip' is not a supported event type for RNTrackPlayer

### ISSUE THREAD

**Issue by tungduonghgg123** [react-native-kit/react-native-track-player#575]
`react-native-track-player` version: ^1.1.3
![image](https://user-images.githubusercontent.com/32666311/56913400-c5c64c00-6adb-11e9-8c86-e5dd403c2392.png)

I have no idea why you don't support this while it is a essential functions and it exists in documentary  :
![image](https://user-images.githubusercontent.com/32666311/56913531-150c7c80-6adc-11e9-9022-c797acd9cd74.png)

**Comment by tungduonghgg123** [comment]
@Guichaguri Hope you fix this soon. Thank you <3

**Comment by curiousdustin** [comment]
@tungduonghgg123 when are you expecting to receive `remote-skip` on iOS?

`remote-skip` is an Android only event that happens when a user selects a track (from a smart watch or other device). 

iOS does not support this functionality. 

You should only add this handler on Android to avoid this error. 

You can use `remote-next` and `remote-previous` to handle skip to next/previous lock screen controls.
