### ISSUE TITLE
Implementing MediaBrowserCompat

### ISSUE THREAD

**Issue by neoassyrian** [react-native-kit/react-native-track-player#598]
I was wondering if MediaBrowserCompat can be implemented. I can help implement it and test it if you someone can point me to the right direction to the right class to implement.
Do I need to implement it in the MetadataManager.java? or have to create a new class that extends the MediaBrowserCompat?

**Comment by Guichaguri** [comment]
This module used to implement MediaBrowserCompat, but due to internal and API changes, we removed it.

The problem is that the service must extend `MediaBrowserServiceCompat`, since it already extends React Native's `HeadlessJsTaskService`, we'd have to extend the media browser service and copy the whole code from the headless JS service into ours. That would make the service code really awful and hard to maintain.
