### ISSUE TITLE
Android memory cleaning the app

### ISSUE THREAD

**Issue by ntk860** [react-native-kit/react-native-track-player#612]
Hello All, I think this issue is related to  https://github.com/tanguyantoine/react-native-music-control/issues/45, Android is constantly restarting the all app after playing for some time. Is there anything I can do to prevent that ?

**Comment by Guichaguri** [comment]
I don't think there is anything we can change other than optimize existing code, we already set the music service as the maximum priority, so it should be the last one to be stopped.

If Android is killing it, it's because it is consuming a lot of memory and the device can't handle that. You can optimize your own code by reducing stored state, reducing the track file size, the artwork file size, the size of the queue, etc.
