### ISSUE TITLE
on iOS play/pause resets the playback speed to 1

### ISSUE THREAD

**Issue by alangumer** [react-native-kit/react-native-track-player#614]
# Configuration
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      Memory: 73.02 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 24.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        API Levels: 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6
      react-native: 0.59.6 => 0.59.6
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

react-native-track-player 1.1.4

# Issue
On iOS whenever the playback is paused and then played the speed is reset to 1.
 
# Code
TrackPlayer.setRate(2); // play at 2x speed
TrackPlayer.play();
TrackPlayer.pause();
TrackPlayer.play(); // the rate is reset to 1

**Comment by jariwalabhavesh** [comment]
@alangumer : I am facing same issue with latest version

**Comment by dhruv-finimize** [comment]
I'm also having this issue - any work-arounds, or fixes? Thanks!

**Comment by HessiPard** [comment]
Faced this issue

**Comment by davidsalib** [comment]
I'm having this issue again with the latest version. It works on Android, but play/pause on iOS resets the speed back to 1.

**Comment by iwater** [comment]
Faced this issue

**Comment by davidsalib** [comment]
any updates on this?

**Comment by fivecar** [comment]
Alright, friends. This is still an issue even in version 3.2.0, but I've taken an afternoon to isolate a specific [minimal-code repro here](https://github.com/SuperphonicHub/TrackPlayerRateExample).

It turns out the following sequence is problematic:
```typescript
  await TrackPlayer.setRate(2);
  await TrackPlayer.play();
  await TrackPlayer.seekTo(position + 15);
  await TrackPlayer.play();
```
Specifically, if you seek while playing, and then call `play()` in the new position, it'll reset the playback rate. I've not debugged into `SwiftAudioEx` enough to figure out the cause, but this is at least a reliable repro.

You can check out the repo above, which includes both the code and instructions to get a quick repro. In the meantime, I'm going to dive into `react-native-track-player` and `SwiftAudioEx` in hopes that inspiration hits.

**Comment by fivecar** [comment]
Okie doke. Fix for this 3+ year bug now submitted in this PR: https://github.com/doublesymmetry/SwiftAudioEx/pull/37.
