### ISSUE TITLE
TrackPlayer.updateOptions crashing app

### ISSUE THREAD

**Issue by fcaride** [react-native-kit/react-native-track-player#665]
When i do the following:     
TrackPlayer.updateOptions({
      stopWithApp: true,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
        TrackPlayer.CAPABILITY_STOP
      ],
      compactCapabilities: [TrackPlayer.CAPABILITY_PLAY, TrackPlayer.CAPABILITY_PAUSE]
    });

It crashes the app in the android version. It crashes because for some reason when i debug the Android side the function updateOptions is called with all values null in the Android side. Like the constants werent there in the JS side. 
Using 2.0-rc10

**Comment by fcaride** [comment]
Yes confirmed, TrackPlayer.CAPABILITY_PLAY is undefined

**Comment by jpolo** [comment]
You should use `TrackPlayer.Capability.Play` instead of `TrackPlayer.CAPABILITY_PLAY`. 

Still, this issue shows a small problem of architecture : the constants does not have the same value between platform. Indeed, they can be undefined if something went wrong during init or if linking was done wrong. This creates sometimes misleading errors that confuse the dev about the real problem...

IMHO, JS constants should have real constant values. iOS & Android native code would do the adapter with the real constants. Don't you think ?

**Comment by fcaride** [comment]
@jpolo  Im getting Undefined is not an object in TrackPlayer.Capability.Play 
V. 2.0.0-rc12

**Comment by dcvz** [comment]
@fcaride I've addressed this issue in the branch regarding `v2` -- constants are now exported differently.

**Comment by Guichaguri** [comment]
> Still, this issue shows a small problem of architecture : the constants does not have the same value between platform

That's intended. The value matches its internal value, that's why you should use the constants instead of their raw value. Treat it as its own type and you don't need to care about the internal value.

**Comment by jpolo** [comment]
Some tests of a third party app can pass when using the constants because expect(State.Buffering).toBe(State.Playing) is true (=== undefined)

It took us some time to introspect the library to understand that the type was lying, those constants can be string number or undefined depending of the runtime...

**Comment by Guichaguri** [comment]
For tests, you should be mocking every native piece, including constants, you can mock them with any unique value (such as `a`, `b`, `c`). It's not a hard thing to do
