### ISSUE TITLE
Support updating URL through `updateMetadataForTrack` / lazy-loading of track urls

### ISSUE THREAD

**Issue by benkaiser** [react-native-kit/react-native-track-player#818]
# Issue

Due to how my app/service works, I fetch the track urls lazily (only when they are played do I attempt to fetch them). I currently am doing a hack whereby I reset the track queue, re-add all the songs, then play the same song again to get it to change the url of just the currently selected song. This would all be fun and well, but the notification disappears during the reset and looks rather ugly.

# Code

Rough psudu of my app:
```
TrackPlayer.add([songs]);
TrackPlayer.play();
// wait for start playing event, if we have the url, all good, if we don't then pause and go fetch it (the track url is initially set to a 10s empty track)
// Once we have the url:
TrackPlayer.reset()
.then(() => this.addPlaylist())
.then(() => TrackPlayer.skip(nextTrack.id))
.then(() => TrackPlayer.play());
```

Here is the literal source-code:
https://github.com/benkaiser/stretto-mobile-next/blob/cfd4c4744e7171c684c5f99184838484951390ca/src/services/player.js#L303

**Comment by Guichaguri** [comment]
If you really don't have the URLs beforehand, I don't see a reason why you should be using the integrated queue. You should manage your own queue and add the tracks as they need to be played, that should actually make it smoother and easier to work with in your case.

The main reason to use the integrated queue is to have gapless playback, where the module will start to buffer the next track before the last one finishes.

**Comment by benkaiser** [comment]
You know what, you are completely right @Guichaguri . I've had my head so deep in this I couldn't see the easy solution!

I'll test it out tomorrow manually managing the queue. Thanks!

**Comment by curiousdustin** [comment]
@benkaiser , can you please reply with your results when you get a chance?

I have been running into related issues. And I'm not sure the solution is as simple as managing the queue manually on the JS side.

A few things I have run into:

- If you use a single track in the integrated queue, waiting for it to end, and then add the next, the playback will stop in between and the notification will disappear and reappear as mentioned. This is not a great user experience.

- Cannot fetch new URL while app is backgrounded, player is stopped (between tracks), and Battery Saver mode is on. 
_**Explanation**: In my case, my track URLs are only valid for X amount of time. Because of this, I was waiting to fetch the URL until right before adding it to the integrated queue. However, when Battery Saver mode is on with the app is in the background, and the player stops because it has reached the end of the queue, the player service shuts down. Because there is no active service running, the OS does not allow the fetch for the next URL to happen in the background (part of battery saving mode). Hope that makes sense._

- With the service starting and stopping often, it seems more likely you would run into this unresolved issue: https://github.com/react-native-kit/react-native-track-player/issues/473

**Comment by curiousdustin** [comment]
I have tried using the integrated queue and it works much better regarding the behavior of the notification, and background + battery saver mode.

However, I will still have to figure out a way to update the URLs of the tracks within the queue, because my URLs expire after X time.

My only solution at this time is to remove and rebuild the queued tracks when necessary.

**Comment by benkaiser** [comment]
@curiousdustin I haven't begun to implement yet, but I can definitely see that the second issue you mention about the background service being an issue. That said, it would be an issue anyway with the current implementation, so no regression there (for my use case at least).

As for the first issue, I don't think I would actually need to stop the track player, here is my rough plan:

Current Track is playing -> When the next track is queued, if it needs a url, place a 'placeholder' track in the queue with the metadata of that track but with an empty soundclip as the url -> when the next track is actually ready, add it as a new track to the queue with the real url, skip to it and play.

It's not super clean, but the notification shouldn't flicker and it should show the 'current track' at any given time.

**Comment by Guichaguri** [comment]
One of the planned features for v2 is the "queue-less player", but I don't see how it would solve this issue. The only thing I can think of is the recently merged `updateNowPlayingMetadata` #634, which allows you to disable the automatic metadata updates and do that by yourself, so you could keep the notification up even without having anything playing.

If that really doesn't work out, it might be a good idea to add a new event:
* `playback-about-to-end` - An event that will be triggered a few seconds (configurable) before the track finishes, allowing you to load the next one in time.

**Comment by benkaiser** [comment]
Thanks for the input @Guichaguri . I've managed to make it almost completely work with your first suggestion of manually managing the queue:

https://github.com/benkaiser/stretto-mobile-next/commit/b40cbe9cd1dfa42775b167a52a8b03c575ee8c84

For keeping the notification up to date, I put a placeholder song in there with the right metadata but wrong url (empty mp3 track instead) and pause it and disable letting the user play it (since it isn't the right song), then I add the real song once it's ready and I have the url and play that. It's actually working quite nicely and the notification stays up to date even if the user skips through a dozen songs in rapid succession. And best of all, no notification flicker!

@curiousdustin this won't really fix the failing to refresh a url when backgrounded that you were facing, but it could be worth a look at my code to see how I got it to not flicker the notification in and out.

**Comment by curiousdustin** [comment]
I'll try to take a look tomorrow. If the notification is sticking around properly, I think that means the service is staying active. I think as long as the service is active, it will keep the app in a state where it IS allowed to make these background fetches. 

So yes, even though hacky, I like your solution. I'll let you know if it works out. :)

**Comment by curiousdustin** [comment]
@benkaiser, can you point me to where in your code you are handling the end of the track, and starting the next one?

I would have guessed you were responding to `playback-queue-ended`, but you have `.next()` commented out.

I'm asking because I'm not having any luck with keeping the notification present. When the track ends, the state of the player changes to stopped, which ultimately results in `stopForeground()` being called on [MusicService](https://github.com/react-native-kit/react-native-track-player/blob/dev/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java#L304).

I am reacting to `playback-queue-ended` by adding my next track, but the notification does go away briefly.

**Comment by benkaiser** [comment]
@curiousdustin good catch! My next code change fixed that:

https://github.com/benkaiser/stretto-mobile-next/commit/2b5277f527f2f1c4510d3d40887a4dd79d607513

I stopped listening for track ended because it kept firing on my placeholder track for some reason.

Also do note, I still have a minor issue where it's throwing on the placeholder track and causing it to skip once, but I'll resolve that one I get a chance.

**Comment by curiousdustin** [comment]
@benkaiser I tried to replicate what you are doing with no luck.

At first I thought maybe it was because you were using `2.x` and I am using a fork of `1.1.x`. However, I could not find a difference that would matter for this case, and you are not using the new `updateNowPlayingMetadata` feature mentioned above anyway.

It was really bugging me why it would behave differently for you, so I downloaded your project and got it to build and run.

Unfortunately, the notification still disappears and reappears between tracks.

I verified that your placeholder track is getting queued, but it doesn't appear to help the notification.

Perhaps this is just a difference in behavior across various devices or android versions? What device and OS are you testing on?

I am testing on a Galaxy S9 with Android 9.

Another thought, perhaps you are referring to the behavior or the lock screen info/controls? These DO behave nicely in your project.

@Guichaguri, Am I correct in thinking that if you only add a single track to the RNTP at a time, the notification will be forced to go away when the queue ends? (in RNTP version `1.1.x`) It doesn't matter how quickly you add another track...

**Comment by Guichaguri** [comment]
It will. We've added in #634 an option `autoUpdateMetadata` which will not update, enable or disable the notification and lockscreen controls unless you intentionally do so with the new `updateNowPlayingMetadata(metadata)` and `clearNowPlayingMetadata()` functions.

In your case, you should disable `autoUpdateMetadata`, call `updateNowPlayingMetadata()` when a track changes and only call `clearNowPlayingMetadata()` when the queue has been ended on your side.

I think it still needs more testing, and I think the automatic player state updates will be a problem, but we'll reshape the feature with feedback we get.

**Comment by benkaiser** [comment]
@curiousdustin I'm using android 10 on a OnePlus 7 pro, pretty close to stock android and yeah my notification persists (it's the same notification on the lock screen and in the notification drawer).

@Guichaguri that is awesome! I'll switch to using that since I'm manually changing the track  / managing the queue now anyway. This way I don't need a "placeholder" track, I can just update the notification whenever a song is switched to even if I haven't queued it in the track player yet. Thanks a bunch for following up on this!

**Comment by curiousdustin** [comment]
As a follow up, here is what I ended up doing for now, since I wasn't having luck with @benkaiser's solution, and I can't switch to `v2` yet.

I implemented a similar placeholder. When I play a track, I add a normal track followed by a silence track to the RNTP queue. I then wait for `playback-track-changed` to occur when it switches to the silence track. Then I pause the silence track, which keeps the MusicService running and the notification in place. Do whatever fetching I need to determine the next normal track (which is possible even in the background, because the service never leaves foreground). Then add another normal track and silence track, skip to it, and play.

**Comment by wlans** [comment]
For anyone that runs across this in 2024 I  figured out a better way of handling this. I created a proxy service that redirects requests to s3 signed urls. Here is an example: 
```

import express from 'express';
import admin from 'firebase-admin';
import rateLimit from 'express-rate-limit';
import { createProxyMiddleware } from 'http-proxy-middleware';
// import * as functions from 'firebase-functions';

const app = express();

// Initialize Firebase Admin with your service account credentials
// const serviceAccount = require('path/to/your/serviceAccountKey.json');
// admin.initializeApp({
//   credential: admin.credential.cert(serviceAccount),
//   // Add other Firebase configurations if needed
// });

// Rate limiting middleware (adjust the options based on your requirements)
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 200, // Limit each IP to 5 requests per windowMs
});
app.use(limiter);

// Middleware to check user authentication
const authenticateUser = async (req: any, res: any, next: any) => {
  try {
    const idToken = req.headers.authorization;
    // TODO put back in prod
    // if (!idToken) {
    //   return res.status(401).json({ error: 'Unauthorized' });
    // }

    // const decodedToken = await admin.auth().verifyIdToken(idToken);
    // req.user = decodedToken;

    next();
  } catch (error) {
    console.error('Authentication error:', error);
    return res.status(401).json({ error: 'Unauthorized' });
  }
};


// Endpoint to get signed URL (replace 'yourBucketName' and adjust file path)
app.get('/song', authenticateUser, async (req: any, res: any) => {
  try {
    // Replace 'yourBucketName' and adjust the filePath based on your requirements
    const bucket = admin.storage().bucket('yourBucketName');
    const filePath = 'your/path/to/song.mp3';

    const file = bucket.file(filePath);
    const [url] = await file.getSignedUrl({
      action: 'read',
      expires: Date.now() + 15 * 60 * 1000, // URL expires in 15 minutes
    });

    res.redirect(url);
  } catch (error) {
    console.error('Error generating signed URL:', error);
    res.status(500).json({ error: 'Internal Server Error' });
  }
});


// Start the server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});

// export const api = functions.https.onRequest(app);
export const api = app



```

**Comment by ser-emejia** [comment]
is another way to do this?
