### ISSUE TITLE
How to play audio file in res/raw on android

### ISSUE THREAD

**Issue by genglei01** [react-native-kit/react-native-track-player#967]
**Describe the bug**
I want to play an audio file in res/raw on android
and use RNFS get path:
  
 ```
 const root = utils.isAndroid() ? RNFS.DocumentDirectoryPath : RNFS.MainBundlePath;
   return `file://${path}`;
```
And get path:
file:///data/user/0/${applicationId}/files/test.mp3"

But the player report:

play-error {"code": "playback-source", "message": "java.io.FileNotFoundException: /data/user/0/${applicationId}/files/test.mp3: open failed: ENOENT (No such file or directory)"}

Who knows how to fix it?
Thanks

**Comment by genglei01** [comment]
I find a workaround way.
```
const path = FileHelper.addPrefix(`${RNFS.DocumentDirectoryPath}/res/${name}`);
RNFS.copyFileRes(file, destpath)

```
copy audio files  from res/raw to some else dir.
But it is so stupid

**Comment by vangthachdinh** [comment]
Me too and I don't know how can fix it? Any solution?

**Comment by Guichaguri** [comment]
I highly encourage you to use the app bundle instead of using Android's res directory. The resources inside the app bundle will be moved into the res directory in the release build and you can reference it through `require`/`import`.

But if you really need to use an audio file inside the res/raw directory, you can set the URL as follows:
* Fully specifying the resource name: `android.resource://[package]/[res type]/[res name]`
    * E.g. `android.resource://com.app.name/raw/filename`
* Specifying the resource id: `android.resource://[package]/[resource_id]`
    * E.g. `android.resource://com.app.name/2`

Let me know if it doesn't work for you.
